version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: .
      target: prod
    command: npm start
    depends_on:
      - db
    ports:
      - 8000:8000
      - 9229:9229
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./:/app
    networks:
      - backend

  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native-password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      - backend

volumes:
  mysql:

networks:
  backend: